version: '3.8'
services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    restart: always
    # depends_on:
    #   - db # Descomente se usar banco em container

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always 